baseURL = 'https://blog.rdls.dev/'
languageCode = 'en-us'
title = 'Nykot`s Journal'
[module]
  [[module.imports]]
    path = "github.com/hugo-sid/hugo-blog-awesome"
[caches]
  [caches.images]
    dir = ':cacheDir/images'

[[params.socialIcons]]
name = "github"
url = "https://github.com/rodlessa"

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/itsnykot"

[[params.socialIcons]]
name = "Rss"
url = "/index.xml"

[params]
  goToTop = true
