baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Nykot`s Journal'
[module]
  [[module.imports]]
    path = "github.com/hugo-sid/hugo-blog-awesome"
[caches]
  [caches.images]
    dir = ':cacheDir/images'
